---
# tasks file for win_service_config
# does not work
#- name: Ensure openssh is installed
#  win_chocolatey:
#    name: "{{ package_name }}"
#    package_params: "{{ parameters }}"
#    state: latest
#  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"

- name: Ensure openssh is installed
  win_command: choco install -f -y openssh -params '"/SSHServerFeature"' -confirm
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"

- name: Ensure openssh is running via services
  win_service:
    name: "{{ service_name }}"
    state: restarted
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"

- name: Ensure the firewall is setup for openssh
  win_firewall_rule:
    name: OpenSSH
    description: OpenSSH Server
    localport: "{{ local_port }}"
    action: allow
    direction: in
    protocol: "{{ protocol_name }}"
    enabled: yes
    state: present

